# Generated by Django 5.1.2 on 2024-11-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='es_vegetariano',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='precio_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='masa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masa',
            name='precio_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pizza',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='tiempo_preparacion',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='masa',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
