# Generated by Django 5.1.2 on 2024-11-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0002_ingrediente_descripcion_ingrediente_es_vegetariano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
