# Generated by Django 5.1.2 on 2024-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0003_pizza_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comensales', models.PositiveIntegerField()),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
