# Generated by Django 5.1.2 on 2024-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0005_rename_numero_comensales_reserva_npersonas'),
    ]

    operations = [
        migrations.AddField(
            model_name='masa',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
