# Generated by Django 5.1.2 on 2024-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0006_masa_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
