# Generated by Django 5.1.2 on 2024-12-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMammaMia', '0007_ingrediente_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='masa',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='masa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Imagen'),
        ),
    ]
